name: celendar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.3 <4.0.0'

dependencies: 
  table_calendar: ^3.0.9
  http: ^1.0.0
  webview_flutter: ^2.0.13
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.22.0
  firebase_auth: ^4.7.3
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.5
  flutter_local_notifications: ^16.1.0
  appwrite: ^11.0.1


dev_dependencies: 
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  flutter_test: 
    sdk: flutter
  mockito: ^5.4.4
  integration_test:
    sdk: flutter


flutter: 
  fonts: 
    - family: WhiteOnBlack
      fonts: 
        - asset: assets/White On Black.ttf
  uses-material-design: true

